# Autogenerated wrapper script for libigl_jll for aarch64-linux-gnu-cxx11
export libigl_a

using GMP_jll
using MPFR_jll
using OpenBLAS32_jll
using ICU_jll
using GLFW_jll
using Libglvnd_jll
JLLWrappers.@generate_wrapper_header("libigl")
JLLWrappers.@declare_file_product(libigl_a)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll, MPFR_jll, OpenBLAS32_jll, ICU_jll, GLFW_jll, Libglvnd_jll)
    JLLWrappers.@init_file_product(
        libigl_a,
        "lib/libigl.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
